name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: npm ci

      - run: npx puppeteer browsers install firefox

      - name: Record Chrome
        run: npm run start.chrome

      - name: Record Firefox
        run: npm run start.firefox
